baseURL = "https://ripbandit.github.io"
languageCode = "en-us"
title = "Ripbandit's blog"
theme = "nuo"
publishDir = "public"

[params]
email = "ripbandit@protonmail.ch"
twitter = "ripbandit_"
avatar = "/img/avatar.png"

[[menu.main]]
name = "Home"
weight = 10
identifier = "home"
url = "/"

[[menu.main]]
name = "Projects"
weight = 20
identifier = "projects"
url = "https://github.com/ripbandit"